CREATE TABLE IF NOT EXISTS JJ_TIPO_ARSENAL (
    IdtipoArsenal INTEGER PRIMARY KEY AUTOINCREMENT,
    Tipo VARCHAR(50),
    ARSENAL VARCHAR(50 ) NOT NULL
);
CREATE TABLE IF NOT EXISTS JJ_COORDENADAS (
    IdCoordenadas   INTEGER PRIMARY KEY AUTOINCREMENT,
    Geoposicion      VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS JJ_HORARIOS (
    IdHorarios INTEGER PRIMARY KEY AUTOINCREMENT,
    Dia VARCHAR(50),
    Hora VARCHAR(50)
);

